const HOT_PLANS: DataBundle[] = [
  // MTN Hot Deals
  {
    id: 228,
    data: "1GB",
    price: 590,
    validity: "30 Days",
    category: "Hot",
    description: "MTN Hot Deal - 1GB for 30 days",
    planType: "MTN",
  },
  {
    id: 246,
    data: "1.2GB",
    price: 500,
    validity: "30 Days",
    category: "Hot",
    description: "MTN Hot Deal - 1.2GB All Socials for 30 days",
    planType: "MTN",
  },
  {
    id: 235,
    data: "2GB",
    price: 1190,
    validity: "30 Days",
    category: "Hot",
    description: "MTN Hot Deal - 2GB for 30 days",
    planType: "MTN",
  },
  {
    id: 265,
    data: "3GB",
    price: 1850,
    validity: "30 Days",
    category: "Hot",
    description: "MTN Hot Deal - 3GB for 30 days",
    planType: "MTN",
  },
  {
    id: 272,
    data: "5GB",
    price: 2980,
    validity: "30 Days",
    category: "Hot",
    description: "MTN Hot Deal - 5GB for 30 days",
    planType: "MTN",
  },
  {
    id: 104,
    data: "6.75GB",
    price: 3000,
    validity: "30 Days",
    category: "Hot",
    description: "MTN Hot Deal - 6.75GB for 30 days",
    planType: "MTN",
  },
  {
    id: 277,
    data: "10GB",
    price: 4650,
    validity: "30 Days",
    category: "Hot",
    description: "MTN Hot Deal - 10GB for 30 days",
    planType: "MTN",
  },
  {
    id: 339,
    data: "20GB",
    price: 7750,
    validity: "30 Days",
    category: "Hot",
    description: "MTN Hot Deal - 20GB for 30 days",
    planType: "MTN",
  },
  // Airtel Hot Deals
  {
    id: 146,
    data: "2GB",
    price: 1490,
    validity: "30 Days",
    category: "Hot",
    description: "Airtel Hot Deal - 2GB for 30 days",
    planType: "AIRTEL",
  },
  {
    id: 148,
    data: "4GB",
    price: 2485,
    validity: "30 Days",
    category: "Hot",
    description: "Airtel Hot Deal - 4GB for 30 days",
    planType: "AIRTEL",
  },
  {
    id: 169,
    data: "10GB",
    price: 3100,
    validity: "30 Days",
    category: "Hot",
    description: "Airtel Hot Deal - 10GB for 30 days",
    planType: "AIRTEL",
  },
  // Glo Hot Deals
  {
    id: 39,
    data: "1GB",
    price: 420,
    validity: "30 Days",
    category: "Hot",
    description: "Glo Hot Deal - 1GB for 30 days",
    planType: "GLO",
  },
  {
    id: 40,
    data: "2GB",
    price: 850,
    validity: "30 Days",
    category: "Hot",
    description: "Glo Hot Deal - 2GB for 30 days",
    planType: "GLO",
  },
  {
    id: 41,
    data: "3GB",
    price: 1200,
    validity: "30 Days",
    category: "Hot",
    description: "Glo Hot Deal - 3GB for 30 days",
    planType: "GLO",
  },
  {
    id: 42,
    data: "5GB",
    price: 2000,
    validity: "30 Days",
    category: "Hot",
    description: "Glo Hot Deal - 5GB for 30 days",
    planType: "GLO",
  },
  {
    id: 43,
    data: "10GB",
    price: 4000,
    validity: "30 Days",
    category: "Hot",
    description: "Glo Hot Deal - 10GB for 30 days",
    planType: "GLO",
  },
  // 9mobile Hot Deals
  {
    id: 70,
    data: "500MB",
    price: 150,
    validity: "30 Days",
    category: "Hot",
    description: "9mobile Hot Deal - 500MB for 30 days",
    planType: "9MOBILE",
  },
  {
    id: 71,
    data: "1GB",
    price: 300,
    validity: "30 Days",
    category: "Hot",
    description: "9mobile Hot Deal - 1GB for 30 days",
    planType: "9MOBILE",
  },
  {
    id: 72,
    data: "2GB",
    price: 600,
    validity: "30 Days",
    category: "Hot",
    description: "9mobile Hot Deal - 2GB for 30 days",
    planType: "9MOBILE",
  },
  {
    id: 73,
    data: "3GB",
    price: 900,
    validity: "30 Days",
    category: "Hot",
    description: "9mobile Hot Deal - 3GB for 30 days",
    planType: "9MOBILE",
  },
  {
    id: 75,
    data: "5GB",
    price: 1500,
    validity: "30 Days",
    category: "Hot",
    description: "9mobile Hot Deal - 5GB for 30 days",
    planType: "9MOBILE",
  },
  {
    id: 76,
    data: "10GB",
    price: 3000,
    validity: "30 Days",
    category: "Hot",
    description: "9mobile Hot Deal - 10GB for 30 days",
    planType: "9MOBILE",
  },
];